apiVersion: v1
kind: Pod
metadata:
  name: kube-demo
spec:
  containers:
    - name: kube-demo
      image: nginx:1.7.9
      volumeMounts:
      - name: config-volume
        mountPath: /config.yaml
        subPath: config.yaml
  volumes:
    - name: config-volume
      configMap:
        name: demo-config
  restartPolicy: Never
